site_name: Git & GitHub - Przewodnik dla Zespołów
theme:
  name: material
  language: pl
  palette:
    - scheme: default
      primary: indigo
      accent: light-blue
      toggle:
        icon: material/brightness-7
        name: Przełącz na tryb ciemny
    - scheme: slate
      primary: indigo
      accent: light-blue
      toggle:
        icon: material/brightness-4
        name: Przełącz na tryb jasny
  features:
    - navigation.tabs
    - navigation.top
    - search.suggest
    - search.highlight
    - content.code.annotate
    - content.tabs.link
nav:
  - Strona Główna: index.md
  - Autorzy: autorzy.md
  - Teoria - Kurs Git i GitHub:
    - Wprowadzenie: index.md
    - Wprowadzenie1: teoria_v1.md
    - Wprowadzenie2: teoria_v2.md
    - Wprowadzenie3: teoria_v3.md
  - Przykłady - Warsztat Praktyczny:
    - Wprowadzenie: przykłady/index.md

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true

    