#Informacje o projekce
site_name: Git & GitHub - Przewodnik dla Zespołów
site_author: Szymon Ślusarczyk, Kacper Augustyniak
site_description: >-
  Kompleksowa instrukcja konfiguracji i pracy z systemem kontroli wersji Git
  oraz platformą GitHub, stworzona z myślą o efektywnej pracy zespołowej.

#Repozytorium
repo_name: Snozlyy11/projekt-git-github-dev
repo_url: https://github.com/Snozlyy11/projekt-git-github-dev

#Konfiguracja
theme:
  name: material
  language: pl
  logo: assets/logo.png
  palette:
    - scheme: default
      primary: black
      accent: light-blue
      toggle:
        icon: material/brightness-7
        name: Przełącz na tryb ciemny
    - scheme: slate
      primary: black
      accent: light-blue
      toggle:
        icon: material/brightness-4
        name: Przełącz na tryb jasny
  features:
    - navigation.tabs
    - navigation.top
    - search.suggest
    - search.highlight
    - content.code.annotate
    - content.tabs.link

#Drzewo stron    
nav:
  - Strona Główna: index.md
  - Autorzy: autorzy.md
  - Teoria - Kurs Git i GitHub:
    - teoria/index.md
    - Git vs Github: teoria/git-vs-github.md
    - Kluczowe pojęcia: teoria/pojecia.md
    - Modele pracy zespołowej: teoria/workflow.md
  - Przykłady - Warsztat Praktyczny:
    - praktyka/index.md
    - Instalacja Gita: praktyka/instalacja.md
    - Konfiguracja Gita: praktyka/konfiguracja.md
    - Praca z repozytorium: praktyka/praca-z-repo.md

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true

plugins:
  - glightbox